In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use("seaborn")

In [2]:
stock2index = {
    "Tesco": "TSCO.L",
    "HSBC": "HSBC",
    "Microsoft": "MSFT",
    "Netflix": "NFLX",
    "Google": "GOOG",
    "BP": "BP",
    "EasyJet": "EZJ.L",
    "Aviva": "AV.L",
    "Legal&General": "LGEN.L",
    "IBM": "IBM",
    "Fairfax": "FFH.TO",
    "Blackstone": "BX",
    "LloydsBank": "LYG",
    "JPMorgan": "JPM"
}

In [3]:
stock_list = [v for v in stock2index.values()]

df = yf.download(stock_list, "2016-01-01")

[*********************100%***********************]  14 of 14 completed

In [9]:
returns = df["Adj Close"].pct_change()
returns = returns.dropna()

returns.head(15)

,AV.L,BP,BX,EZJ.L,FFH.TO,GOOG,HSBC,IBM,JPM,LGEN.L,LYG,MSFT,NFLX,TSCO.L
Date,,,,,,,,,,,,,,
2016-01-05,0.004823,-0.004185,-0.027979,0.014393,-0.006557,0.000998,-0.002332,-0.000736,0.001729,0.009649,-0.004630,0.004562,-0.020917,0.015114
2016-01-06,-0.009400,-0.020369,-0.030206,-0.002270,0.006897,0.001400,-0.034546,-0.005006,-0.014436,-0.020260,-0.027907,-0.018165,0.093071,-0.019737
2016-01-07,-0.027054,-0.028713,-0.033346,-0.050626,0.016426,-0.023170,-0.020985,-0.017090,-0.040439,-0.034725,-0.023924,-0.034783,-0.026513,-0.016601
2016-01-08,-0.010376,-0.017669,-0.033359,0.026363,-0.005986,-0.016410,-0.006595,-0.009258,-0.022399,-0.005659,0.000000,0.003067,-0.027671,0.055316
2016-01-11,-0.006710,-0.002421,-0.033333,0.002919,0.008020,0.002184,0.007746,0.012155,-0.001527,-0.004878,0.009804,-0.000573,0.032139,-0.009871
2016-01-12,0.014777,-0.006588,0.021095,0.001164,0.021582,0.014022,0.004941,-0.002477,0.002210,0.003676,-0.009709,0.009178,0.014004,0.067033
2016-01-13,0.002288,0.004189,-0.028606,-0.017442,-0.034464,-0.035134,-0.017482,-0.013017,-0.027476,0.007733,-0.046569,-0.021599,-0.085950,0.019974
2016-01-14,-0.014944,0.071602,0.048671,-0.028402,0.025942,0.020212,0.012511,0.013265,0.014998,-0.009693,0.007712,0.028466,0.004692,0.061276
2016-01-15,-0.021281,-0.054168,-0.042121,-0.018270,0.014880,-0.028361,-0.049149,-0.021668,-0.019931,-0.024878,-0.035714,-0.039917,-0.028208,-0.021131
2016-01-18,-0.003014,0.000000,0.000000,-0.006824,-0.001580,0.000000,0.000000,0.000000,0.000000,-0.000418,0.000000,0.000000,0.000000,-0.017634
2016-01-19,0.025265,-0.008231,-0.022394,0.019363,0.024872,0.010569,-0.000289,-0.014766,-0.000526,0.023012,-0.005291,-0.008433,0.037005,-0.015166
2016-01-20,-0.051601,-0.015906,-0.010828,-0.006740,0.010427,-0.004759,-0.032351,-0.048786,-0.026311,-0.044172,-0.023936,0.004549,-0.001390,-0.042112
2016-01-21,0.021541,0.035137,0.017263,0.005552,-0.002795,0.011654,0.000298,0.008617,-0.004684,0.009414,0.013624,-0.006103,-0.050028,0.023950
2016-01-22,0.026087,0.030211,0.084851,0.006135,-0.005648,0.026408,0.031036,-0.003336,0.030769,0.008902,0.043011,0.035856,-0.015926,0.028837
2016-01-25,-0.016949,-0.028995,-0.045021,-0.005488,0.006325,-0.018725,-0.029523,-0.003428,-0.022652,-0.013866,-0.056701,-0.009562,-0.015886,-0.030209

In [10]:
td_year = (returns.count() / ((returns.index[-1] - returns.index[0]).days / 365.25)).iloc[0]

td_year

258.50023158869845

In [40]:
TMR = 0   # target mean returns, assuming no negative returns

In [41]:
excess_returns = returns - TMR

excess_returns.head(15)

,AV.L,BP,BX,EZJ.L,FFH.TO,GOOG,HSBC,IBM,JPM,LGEN.L,LYG,MSFT,NFLX,TSCO.L
Date,,,,,,,,,,,,,,
2016-01-05,0.004823,-0.004185,-0.027979,0.014393,-0.006557,0.000998,-0.002332,-0.000736,0.001729,0.009649,-0.004630,0.004562,-0.020917,0.015114
2016-01-06,-0.009400,-0.020369,-0.030206,-0.002270,0.006897,0.001400,-0.034546,-0.005006,-0.014436,-0.020260,-0.027907,-0.018165,0.093071,-0.019737
2016-01-07,-0.027054,-0.028713,-0.033346,-0.050626,0.016426,-0.023170,-0.020985,-0.017090,-0.040439,-0.034725,-0.023924,-0.034783,-0.026513,-0.016601
2016-01-08,-0.010376,-0.017669,-0.033359,0.026363,-0.005986,-0.016410,-0.006595,-0.009258,-0.022399,-0.005659,0.000000,0.003067,-0.027671,0.055316
2016-01-11,-0.006710,-0.002421,-0.033333,0.002919,0.008020,0.002184,0.007746,0.012155,-0.001527,-0.004878,0.009804,-0.000573,0.032139,-0.009871
2016-01-12,0.014777,-0.006588,0.021095,0.001164,0.021582,0.014022,0.004941,-0.002477,0.002210,0.003676,-0.009709,0.009178,0.014004,0.067033
2016-01-13,0.002288,0.004189,-0.028606,-0.017442,-0.034464,-0.035134,-0.017482,-0.013017,-0.027476,0.007733,-0.046569,-0.021599,-0.085950,0.019974
2016-01-14,-0.014944,0.071602,0.048671,-0.028402,0.025942,0.020212,0.012511,0.013265,0.014998,-0.009693,0.007712,0.028466,0.004692,0.061276
2016-01-15,-0.021281,-0.054168,-0.042121,-0.018270,0.014880,-0.028361,-0.049149,-0.021668,-0.019931,-0.024878,-0.035714,-0.039917,-0.028208,-0.021131
2016-01-18,-0.003014,0.000000,0.000000,-0.006824,-0.001580,0.000000,0.000000,0.000000,0.000000,-0.000418,0.000000,0.000000,0.000000,-0.017634
2016-01-19,0.025265,-0.008231,-0.022394,0.019363,0.024872,0.010569,-0.000289,-0.014766,-0.000526,0.023012,-0.005291,-0.008433,0.037005,-0.015166
2016-01-20,-0.051601,-0.015906,-0.010828,-0.006740,0.010427,-0.004759,-0.032351,-0.048786,-0.026311,-0.044172,-0.023936,0.004549,-0.001390,-0.042112
2016-01-21,0.021541,0.035137,0.017263,0.005552,-0.002795,0.011654,0.000298,0.008617,-0.004684,0.009414,0.013624,-0.006103,-0.050028,0.023950
2016-01-22,0.026087,0.030211,0.084851,0.006135,-0.005648,0.026408,0.031036,-0.003336,0.030769,0.008902,0.043011,0.035856,-0.015926,0.028837
2016-01-25,-0.016949,-0.028995,-0.045021,-0.005488,0.006325,-0.018725,-0.029523,-0.003428,-0.022652,-0.013866,-0.056701,-0.009562,-0.015886,-0.030209

In [42]:
excess_returns = excess_returns.apply(lambda r: np.where(r < 0, r, 0))

excess_returns

,AV.L,BP,BX,EZJ.L,FFH.TO,GOOG,HSBC,IBM,JPM,LGEN.L,LYG,MSFT,NFLX,TSCO.L
Date,,,,,,,,,,,,,,
2016-01-05,0.000000,-0.004185,-0.027979,0.000000,-0.006557,0.000000,-0.002332,-0.000736,0.000000,0.000000,-0.004630,0.000000,-0.020917,0.000000
2016-01-06,-0.009400,-0.020369,-0.030206,-0.002270,0.000000,0.000000,-0.034546,-0.005006,-0.014436,-0.020260,-0.027907,-0.018165,0.000000,-0.019737
2016-01-07,-0.027054,-0.028713,-0.033346,-0.050626,0.000000,-0.023170,-0.020985,-0.017090,-0.040439,-0.034725,-0.023924,-0.034783,-0.026513,-0.016601
2016-01-08,-0.010376,-0.017669,-0.033359,0.000000,-0.005986,-0.016410,-0.006595,-0.009258,-0.022399,-0.005659,0.000000,0.000000,-0.027671,0.000000
2016-01-11,-0.006710,-0.002421,-0.033333,0.000000,0.000000,0.000000,0.000000,0.000000,-0.001527,-0.004878,0.000000,-0.000573,0.000000,-0.009871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-29,0.000000,0.000000,0.000000,0.000000,-0.004794,0.000000,0.000000,0.000000,-0.004323,0.000000,0.000000,0.000000,-0.002704,-0.000537
2021-11-30,0.000000,-0.008403,-0.049906,-0.012137,0.000000,-0.025063,-0.005747,-0.011814,-0.014886,-0.010530,-0.008163,-0.017943,-0.033050,-0.008065
2021-12-01,0.000000,-0.008475,-0.026865,0.000000,-0.004956,-0.005855,0.000000,-0.001537,-0.005918,0.000000,-0.004115,-0.001543,-0.037592,0.000000
2021-12-02,-0.007860,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000171,0.000000,-0.010471,0.000000,-0.001787,-0.002104,-0.001079
2021-12-03,0.000000,-0.005543,-0.042410,-0.005648,0.000000,-0.008736,-0.008374,0.000000,-0.018113,0.000000,-0.028226,-0.019667,-0.023261,0.000000

In [43]:
downsize_deviations = excess_returns.apply(lambda r: np.sqrt(np.mean(r**2)))

downsize_deviations

AV.L      0.012667
BP        0.014609
BX        0.013744
EZJ.L     0.021864
FFH.TO    0.011145
GOOG      0.011243
HSBC      0.011091
IBM       0.011547
JPM       0.012206
LGEN.L    0.015218
LYG       0.017706
MSFT      0.011188
NFLX      0.016285
TSCO.L    0.010646
dtype: float64

## Sortino Ratio

In [44]:
mean_returns = returns.mean()

mean_returns

AV.L      0.000281
BP        0.000378
BX        0.001428
EZJ.L    -0.000153
FFH.TO    0.000108
GOOG      0.001012
HSBC      0.000131
IBM       0.000242
JPM       0.000867
LGEN.L    0.000556
LYG       0.000075
MSFT      0.001366
NFLX      0.001413
TSCO.L    0.000620
dtype: float64

In [45]:
sortino = (mean_returns - TMR) / downsize_deviations * np.sqrt(td_year)

In [46]:
sortino

AV.L      0.356904
BP        0.415824
BX        1.670208
EZJ.L    -0.112598
FFH.TO    0.156393
GOOG      1.447828
HSBC      0.189487
IBM       0.337441
JPM       1.141553
LGEN.L    0.587923
LYG       0.067835
MSFT      1.962417
NFLX      1.395125
TSCO.L    0.936425
dtype: float64

In [50]:
summary = pd.DataFrame(data={"returns": mean_returns, 
                             "risk": downsize_deviations, 
                            "sortino": sortino})

summary

         returns      risk   sortino
AV.L    0.000281  0.012667  0.356904
BP      0.000378  0.014609  0.415824
BX      0.001428  0.013744  1.670208
EZJ.L  -0.000153  0.021864 -0.112598
FFH.TO  0.000108  0.011145  0.156393
GOOG    0.001012  0.011243  1.447828
HSBC    0.000131  0.011091  0.189487
IBM     0.000242  0.011547  0.337441
JPM     0.000867  0.012206  1.141553
LGEN.L  0.000556  0.015218  0.587923
LYG     0.000075  0.017706  0.067835
MSFT    0.001366  0.011188  1.962417
NFLX    0.001413  0.016285  1.395125
TSCO.L  0.000620  0.010646  0.936425

In [51]:
summary[summary["sortino"] > 1].sort_values(by=["sortino"], ascending=False)

       returns      risk   sortino
MSFT  0.001366  0.011188  1.962417
BX    0.001428  0.013744  1.670208
GOOG  0.001012  0.011243  1.447828
NFLX  0.001413  0.016285  1.395125
JPM   0.000867  0.012206  1.141553